### ISSUE TITLE
Cannot to determine of version - echo said me

### ISSUE THREAD

**Issue by romankrv** [dimitri/el-get#2278] opened 2015-10-29 13:20 UTC
Hi everyone. 
Who knows why I get a message in the echo area. 
I installed magit via el-get
Thanks
Where's a solution for fix it?

![screen shot 2015-10-29 at 3 11 01 pm](https://cloud.githubusercontent.com/assets/42733/10819359/36c85226-7e50-11e5-90a3-4ce76edc0fd9.png)

**Comment by npostavs** [comment] 2015-10-29 23:43
I think it might be because your `~/.emacs.d/el-get/magit/.git` repo doesn't have tags. But I tried a test install of magit in a fresh el-get instance, and the tags do appear, and `magit-version` gives the right answer.

Can you post output from doing
`M-x el-get-cd magit RET`
`M-! git tag RET`

**Comment by romankrv** [comment] 2015-10-30 23:18
npostavs:
Of course I done as you ask me, next screen M-x el-get-cd magic RET
![screen shot 2015-10-31 at 1 15 45 am](https://cloud.githubusercontent.com/assets/42733/10860138/4435bd9a-7f6d-11e5-83c2-4c3a9b567c5c.png)

**Comment by romankrv** [comment] 2015-10-30 23:19
And M-! git tag RET
![screen shot 2015-10-31 at 1 16 25 am](https://cloud.githubusercontent.com/assets/42733/10860154/72b2b2ae-7f6d-11e5-985b-f2d5c9715c4d.png)

**Comment by romankrv** [comment] 2015-10-30 23:23
npostavs: I'll wait your answer eagerly 
Thanking you!

**Comment by vyp** [comment] 2015-10-31 00:54
@romankrv If it helps, I think that means the repo has no tags just as npostavs first thought.

**Comment by npostavs** [comment] 2015-10-31 01:12
> I think that means the repo has no tags just as npostavs first thought.

Yup. I'm not sure why though. Mabye if you run `git fetch --tags` from `~/.emacs.d/el-get/magit/` it will be fixed.

**Comment by romankrv** [comment] 2015-10-31 07:55
Guys, what are you talking about TAGS? You mean - get tags? 
What is general reasons that you have tags but I no have?
Thanks

**Comment by vyp** [comment] 2015-10-31 08:07
@romankrv As npostavs said, try running

    $ cd ~/.emacs.d/el-get/magit
    $ git fetch --tags

And see if that fixes the issue.

We are talking about *git* tags: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by vyp** [comment] 2015-10-31 08:10
And if that does fix the issue, maybe the reason could be because an older version of git you are using does not download the tags on a `git clone`. Just guessing. Which version of git do you have? (`git --version`)

**Comment by romankrv** [comment] 2015-10-31 09:51
vyp: 
my git version is:
admin@air ~
└> git --version
git version 2.4.4
Anyway I don't understand what reasons are between our config el-get and magit and my?
Thanks

**Comment by vyp** [comment] 2015-10-31 09:55
Hmm that's not old at all, so it wouldn't be because of what I thought...

Anyway, did `git fetch --tags` fix the issue, or not?

**Comment by romankrv** [comment] 2015-10-31 09:59
vyp: After your advice about git fetch in magit folder I have 
next screenshot:
![screen shot 2015-10-31 at 11 53 31 am](https://cloud.githubusercontent.com/assets/42733/10862969/69ef83e6-7fc6-11e5-845b-2b611c47f95b.png)

That is- before launch command git fetch --tags 
I have output is null
after that I have it 
It's a really weird situation. Weird bug. One needs to comprehend,

**Comment by vyp** [comment] 2015-10-31 10:05
Yes that looks good now.

You're right though, it's a weird situation, I'm not sure why the tags were not there already. When I `git clone https://github.com/magit/magit` and then do `cd magit` and then `git tag`, I see all the tags there, so I cannot reproduce it either. (I am using git 2.5.2, but I do not think it should make a difference..)

Maybe @npostavs has some more ideas about the cause of this?

If you uninstall magit, and then try *reinstalling* using the same method, does the issue happen again? Because if you cannot reproduce it, maybe it was just a weird 'one-off' situation..

**Comment by romankrv** [comment] 2015-10-31 10:32
vyp:
Also I want to notice that my configuration have next
(setq el-get-git-shallow-clone t)
But I comment this string and try reinstall my conf 
So, I not get a message about - Cannot determine Magit's version as I put screenshot in at the beginning.

Now I have another message - see screenshot 
And my IMPORTANT question in that a new problem are - 
It's remains as before a very slow start command - M-x magit-status
![screen shot 2015-10-31 at 12 22 09 pm](https://cloud.githubusercontent.com/assets/42733/10863106/3b9dead2-7fcb-11e5-92a5-cec226101889.png)

Please what your idea what  problem is?

Thanking you

**Comment by vyp** [comment] 2015-10-31 10:45
> Also I want to notice that my configuration have next
> (setq el-get-git-shallow-clone t)

Yes this is the reason for the original problem, setting `el-get-git-shallow-clone` will `git clone` with `--depth 1`, meaning only the *latest* commit gets downloaded, and no tags. So this was the reason why your magit repo did not have any tags. Now that you reinstalled with `el-get-git-shallow-clone`, it should be okay now.

The slowness issue with magit is most likely a problem with the new magit itself. See https://github.com/magit/magit/issues/2104 for more. It might not be an el-get issue, unless @npostavs knows more. (Also, maybe it is just slow the first time you do `magit-status` on a repository, maybe after that it is faster?) There's nothing more I can suggest about it being slow though.

**Comment by npostavs** [comment] 2015-10-31 13:15
> Now that you reinstalled without el-get-git-shallow-clone, it should be okay now.

Ah yes, I didn't think of the shallow clone case. Also, note that running `git fetch --tags` made your repository non-shallow (you can see it downloaded 11MiB of history), so it was already fixed at that point. It would be nice if el-get could make a shallow clone and also get the last tag, but I'm not sure if that's possible.

> It's remains as before a very slow start command - M-x magit-status

If it seems like nothing happens (i.e. CPU usage is around 0%) for about 20 seconds only on the first call to `magit-status`, it could be http://magit.vc/manual/magit/Emacs-245-hangs-when-loading-Magit.html; otherwise, I agree with what @vyp said.

**Comment by npostavs** [comment] 2015-10-31 15:52
> It would be nice if el-get could make a shallow clone and also get the last tag, but I'm not sure if that's possible.

Seems like the following might work
```elisp
(defun el-get-git-deepen-to-tag (package)
  (let* ((default-directory (el-get-package-directory package))
         (old-depth
          (ignore-errors
            (string-to-number
             (car (process-lines
                   "git" "rev-list" "HEAD" "--count")))))
         (new-depth nil))
    (when old-depth
      (while (and (/= (call-process "git" nil nil nil "describe" "--tags") 0)
                  (not (eq new-depth old-depth)))
        (setq old-depth (or new-depth old-depth))
        (call-process "git" nil nil nil
                      "fetch" (format "--depth=%d" (+ old-depth 50)))
        (setq new-depth
              (string-to-number
               (car (process-lines
                     "git" "rev-list" "HEAD" "--count"))))))))

(add-hook 'el-get-post-install-hook #'el-get-git-deepen-to-tag)
```

**Comment by romankrv** [comment] 2015-10-31 22:33
Guys, could you please, explain me, Why does tags use in magit? Why another plugin works without tags?

**Comment by vyp** [comment] 2015-10-31 23:38
Tags are just a way for developers to give a 'name' to a specific commit, so that they can be referred to by that name, instead of the commit hash. So one usage for tags is to use it for specifying the version numbers of the package at certain points in history.

I figured that another package might work without tags because the authors of that package simply do not use tags themselves, but the magit recipe (https://github.com/dimitri/el-get/blob/master/recipes/magit.rcp) does not seem to specify any particular tag to use, so I thought it should be working even with a shallow clone...

So it comes down to what exactly is causing the error message "Cannot determine Magit's version...". Maybe @npostavs you know more about how el-get works here? (Because I'm assuming magit's `magit-version` command just parses a `;; Version:` header or uses something like [this](https://github.com/magit/magit/blob/0afd59006b4bceb33ed394a845ef4627d192e274/lisp/magit.el#L96) to determine the version, not somehow looking up the latest local available tag.)

**Comment by npostavs** [comment] 2015-11-01 00:01
> Because I'm assuming magit's magit-version command just parses a ;; Version: header or uses something like this to determine the version, not somehow looking up the latest local available tag.)

Nope, actually magit does use the local git tags for version: https://github.com/magit/magit/blob/0afd59006b4bceb33ed394a845ef4627d192e274/lisp/magit.el#L2544-L2546

**Comment by vyp** [comment] 2015-11-01 00:50
@npostavs Thanks. That doesn't seem like a good way, what if it's just a 'snapshot' without any `.git` directory, right? Anyways, @romankrv I guess that answers your question. It's because magit itself checks for available tags and there's nothing el-get can do about it. Normally I don't think most packages do this, and so they work will still work with a shallow clone.

**Comment by npostavs** [comment] 2015-11-01 01:26
> That doesn't seem like a good way, what if it's just a 'snapshot' without any .git directory, right?

There are some alternate sources for the version number, e.g. if you `make dist` it creates a tarball with a `lisp/magit-version.el` file. If you install via package.el, then the version is extracted from the package descriptor. But not every permutation of install procedures is supported by magit, e.g. if you get a tarball by doing `git archive` it won't work.

**Comment by vyp** [comment] 2015-11-01 02:31
> if you get a tarball by doing git archive it won't work.

Yes this was what I was thinking of. Nevertheless, it's good to know there are some other alternate ways, thanks for clarifying.

**Comment by romankrv** [comment] 2015-11-13 21:44
Hi again, 
As I've got a information about slow work magit from here from the topic and the temporary decision is setting of old version magit <21 but how make it on the el-get receipt? How set a certain version github person (tag, branch, hash)
Thanking for help

**Comment by romankrv** [comment] 2015-11-13 22:28
So I try like:

![screen shot 2015-11-14 at 12 25 42 am](https://cloud.githubusercontent.com/assets/42733/11159228/81156914-8a66-11e5-9f94-508ba5d61603.png)
but it not correct 
could you please help me how to get tag/branch/hash in el-get

**Comment by npostavs** [comment] 2015-11-13 22:49
Don't change `:url`, just add a `:checkout` property with whichever version you want
```
:checkout

    For `git' or `hg' recipes, a branch name, tag, or other valid
    argument to `git checkout'/`hg update'. If provided, this
    overrides any value for the `:branch' property. Unlike the
    `:branch' property, this can be any valid argument to
    `checkout', including a tag name or a commit hash.

    When given a commit hash or tag, this will lock the repo at
    that specific revision. When given a branch name, this will
    always update the repo to the latest version of that branch,
    regardless of any changes made locally (in contrast to simply
    using the `:branch' property, which will cause el-get-to try
    to merge your local changes).
```

**Closed** 2016-05-10 23:11 UTC
Labels: support
