### ISSUE TITLE
Installing magit from master breaks

### ISSUE THREAD

**Issue by thoni56** [dimitri/el-get#2606] opened 2018-01-19 12:25 UTC
I'm not sure if it is the `magit.rcp` that needs fixing or the magit release procedure, but I installed `magit` using `el-get`and got a magit that did not work.

It turned out that the latest master had breaking changes. Manually checking out latest tagged version fixed magit.

So, since the `magit` working model is such that master might have breaking changes, but they create tags for latest official version, the recipe could consider using the latest release instead.

**Comment by npostavs** [comment] 2018-01-19 13:23
Duplicate of #2482.

PS magit `master` is usually in a working state, lately there have been some changes such that it might help to delete all of magit's elc files and recompile.

**Closed by npostavs** 2018-01-19 13:23 UTC

**Comment by thoni56** [comment] 2018-01-22 07:28
Sorry, should have thought that. Thanks for the tip.
